# Generated by Django 3.1.9 on 2021-12-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
        ('purchase_order', '0001_initial'),
        ('customer_order', '0002_auto_20211229_1841'),
        ('item', '0002_auto_20211229_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermain',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordermain',
            name='customer_order_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_order.ordermain'),
        ),
        migrations.AddField(
            model_name='purchaseordermain',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='customer_order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_order.orderdetail'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='purchase_order_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_details', to='purchase_order.purchaseordermain'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.unit'),
        ),
    ]
