# Generated by Django 3.1.9 on 2022-01-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.custom_lib.functions.field_value_validation


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211229_1841'),
        ('item', '0015_auto_20220113_1653'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_order', '0010_auto_20220111_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='informed',
            field=models.BooleanField(default=False, help_text='default = false'),
        ),
        migrations.AddField(
            model_name='purchaseordermain',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseOrderMain_assigned_to', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='purchaseordermain',
            name='purchase_order_type',
            field=models.PositiveIntegerField(choices=[(1, 'ORDER'), (2, 'CANCELLED'), (3, 'RECEIVED')], help_text='Order type like Order, approved, cancelled'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceivedMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('purchase_receive_order_type', models.PositiveIntegerField(choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED')], help_text='1 =unverified, 2 = verified')),
                ('purchase_receive_no', models.CharField(help_text='receive no  should be max. of  20 characters', max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total  amount default=0.00', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='Remarks should be max. of 100 characters', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.purchaseordermain')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceivedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator])),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate  default 0.00', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00 , amount means cost of item', max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, help_text='default =0.00 , sub_total means amount(cost)*qty ', max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('item_unit', models.ForeignKey(blank=True, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.PROTECT, to='item.itemunit')),
                ('purchase_order_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.purchaseorderdetail')),
                ('purchase_order_received_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_received_details', to='purchase_order.purchaseorderreceivedmain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
