# Generated by Django 3.1.9 on 2022-01-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0012_auto_20220116_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderreceiveddetail',
            name='ref_purchase_order_received_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.purchaseorderreceiveddetail'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceivedmain',
            name='ref_purchase_order_received_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_order.purchaseorderreceivedmain'),
        ),
    ]
