# Generated by Django 3.1.9 on 2021-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='First name can be max. of 40 characters', max_length=40)),
                ('address', models.CharField(help_text='Address can be max. of 50 character', max_length=50)),
                ('phone_no', models.CharField(help_text='Phone no. can be max. of 15 characters', max_length=15)),
                ('latitude', models.CharField(blank=True, help_text='Can be blank', max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Can be blank', max_length=30, null=True)),
                ('active', models.BooleanField(default=True, help_text='by default active = True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('contact_person', models.CharField(help_text='Contact Person  can be max. of 50 characters', max_length=50)),
                ('phone_no', models.CharField(blank=True, help_text='Phone no. can be max. of 15 characters and blank = True', max_length=15, null=True)),
                ('active', models.BooleanField(default=True, help_text='by default active = True')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
