# Generated by Django 3.1.9 on 2022-01-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_pan_vat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='pan_vat_no',
            field=models.CharField(help_text='Pan vat no. can be max. of 10 characters and unique = true', max_length=10, unique=True),
        ),
    ]
