# Generated by Django 3.1.9 on 2022-01-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211229_1841'),
        ('log_app', '0007_auto_20220103_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchasemain',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='null= True, blank = True', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier'),
        ),
    ]
