# Generated by Django 3.1.9 on 2022-01-03 13:51

from django.db import migrations, models
import src.company.models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0008_auto_20220103_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcompany',
            name='brand_image',
            field=models.TextField(blank=True, help_text='blank  true', max_length=100, validators=[src.company.models.validate_image]),
        ),
    ]
