# Generated by Django 3.1.9 on 2022-01-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0013_auto_20220107_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='item_unit',
        ),
    ]
