# Generated by Django 3.1.9 on 2022-01-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0014_remove_logitem_item_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logitemunit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical item unit'},
        ),
        migrations.AlterModelTable(
            name='logitemunit',
            table='item_item_Unit_log',
        ),
    ]
