# Generated by Django 3.1.9 on 2022-01-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0015_auto_20220107_2001'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logitemunit',
            table='item_product_Unit_log',
        ),
    ]
