# Generated by Django 3.1.9 on 2022-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0018_auto_20220107_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logorderdetail',
            name='unit',
        ),
    ]
