# Generated by Django 3.1.9 on 2022-01-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0020_logorderdetail_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='item_unit',
        ),
        migrations.RemoveField(
            model_name='logorderdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logpurchasedetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logpurchaseorderdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logsaledetail',
            name='unit',
        ),
    ]
