# Generated by Django 3.1.9 on 2022-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0022_auto_20220107_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchasedetail',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate  default 0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate  default 0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
