# Generated by Django 3.1.9 on 2022-01-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20220109_1439'),
        ('log_app', '0023_auto_20220109_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logorderdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logpurchasedetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logpurchaseorderdetail',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='logsaledetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='logorderdetail',
            name='item_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemunit'),
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='item_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemunit'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='item_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemunit'),
        ),
        migrations.AddField(
            model_name='logsaledetail',
            name='item_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemunit'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='item_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemunit'),
        ),
    ]
