# Generated by Django 3.1.9 on 2022-01-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0024_auto_20220109_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpurchaseorderdetail',
            name='customer_order_detail',
        ),
        migrations.RemoveField(
            model_name='logpurchaseordermain',
            name='customer_order_main',
        ),
    ]
