# Generated by Django 3.1.9 on 2022-01-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import src.custom_lib.functions.field_value_validation


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211229_1841'),
        ('purchase_order', '0010_auto_20220111_1255'),
        ('item', '0015_auto_20220113_1653'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_app', '0026_auto_20220111_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='logorderdetail',
            name='informed',
            field=models.BooleanField(default=False, help_text='default = false'),
        ),
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='informed',
            field=models.BooleanField(default=False, help_text='default = false'),
        ),
        migrations.AddField(
            model_name='logpurchaseordermain',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Max value  price can be upto 9999999999.99, price means MRP', max_digits=12),
        ),
        migrations.AlterField(
            model_name='logpurchaseordermain',
            name='purchase_order_type',
            field=models.PositiveIntegerField(choices=[(1, 'ORDER'), (2, 'CANCELLED'), (3, 'RECEIVED')], help_text='Order type like Order, approved, cancelled'),
        ),
        migrations.CreateModel(
            name='LogPurchaseOrderReceivedMain',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('purchase_receive_order_type', models.PositiveIntegerField(choices=[(1, 'UNVERIFIED'), (2, 'VERIFIED')], help_text='1 =unverified, 2 = verified')),
                ('purchase_receive_no', models.CharField(db_index=True, help_text='receive no  should be max. of  20 characters', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total  amount default=0.00', max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='Remarks should be max. of 100 characters', max_length=100)),
                ('history_user_id', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('purchase_order_main', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase_order.purchaseordermain')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier.supplier')),
            ],
            options={
                'verbose_name': 'historical purchase order received main',
                'db_table': 'purchase_order_purchaseorderreceivedmain_log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LogPurchaseOrderReceivedDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator])),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate  default 0.00', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00 , amount means cost of item', max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, help_text='default =0.00 , sub_total means amount(cost)*qty ', max_digits=12)),
                ('history_user_id', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.item')),
                ('item_unit', models.ForeignKey(blank=True, db_constraint=False, help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemunit')),
                ('purchase_order_detail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase_order.purchaseorderdetail')),
            ],
            options={
                'verbose_name': 'historical purchase order received detail',
                'db_table': 'purchase_order_purchaseorderreceiveddetail_log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
