# Generated by Django 3.1.9 on 2022-01-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0027_auto_20220113_1653'),
        ('purchase_order', '0011_auto_20220113_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchaseorderreceiveddetail',
            name='purchase_order_received_main',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase_order.purchaseorderreceivedmain'),
        ),
    ]
