# Generated by Django 3.1.9 on 2022-01-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0028_logpurchaseorderreceiveddetail_purchase_order_received_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logpurchaseorderreceivedmain',
            old_name='purchase_receive_order_type',
            new_name='purchase_order_receive_type',
        ),
    ]
