# Generated by Django 3.1.9 on 2022-01-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0012_auto_20220116_1004'),
        ('log_app', '0029_auto_20220116_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpurchasedetail',
            name='ref_purchase_order_detail',
        ),
        migrations.RemoveField(
            model_name='logpurchasemain',
            name='ref_purchase_order_main',
        ),
        migrations.AddField(
            model_name='logpurchasedetail',
            name='ref_purchase_order_received_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase_order.purchaseorderreceiveddetail'),
        ),
        migrations.AddField(
            model_name='logpurchasemain',
            name='ref_purchase_order_received_main',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase_order.purchaseorderreceivedmain'),
        ),
        migrations.AlterField(
            model_name='logordermain',
            name='delivery_status',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'CANCELLED'), (3, 'BILLED'), (4, 'PACKED'), (5, 'DISPATCHED'), (6, 'DONE')], default=1, help_text='Where 1 = PENDING, 2 = CANCELLED,  3 = BILLED,  4 = PACKED, 5 =DISPATCHED, 6=DONE,  Default=1'),
        ),
    ]
