# Generated by Django 3.1.9 on 2022-01-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0032_auto_20220119_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchasemain',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text=' discount amount default=0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='logpurchasemain',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text=' vat amount default=0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='logsupplier',
            name='pan_vat_no',
            field=models.CharField(default='1234', help_text='Pan vat no. can be max. of 10 characters', max_length=10),
            preserve_default=False,
        ),
    ]
