# Generated by Django 3.1.9 on 2022-01-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0033_auto_20220119_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchaseorderdetail',
            name='available',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'RECEIVED'), (3, 'VERIFIED'), (4, 'CANCELLED')], default=1, help_text='available like pending, approved, purchased, default = 1'),
        ),
    ]
