# Generated by Django 3.1.9 on 2022-01-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0033_auto_20220119_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsupplier',
            name='pan_vat_no',
            field=models.CharField(db_index=True, help_text='Pan vat no. can be max. of 10 characters and unique = true', max_length=10),
        ),
    ]
