# Generated by Django 3.1.9 on 2022-01-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0034_auto_20220120_1237'),
        ('log_app', '0034_auto_20220120_1230'),
    ]

    operations = [
    ]
