# Generated by Django 3.1.9 on 2022-01-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0035_merge_20220120_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsalemain',
            name='ref_purchase_main',
        ),
    ]
