# Generated by Django 3.1.9 on 2022-01-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0039_auto_20220130_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcustomer',
            name='phone_no',
            field=models.CharField(db_index=True, help_text='Phone no. can be max. of 15 characters and unique = True', max_length=15),
        ),
    ]
