# Generated by Django 3.1.9 on 2022-02-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0040_auto_20220130_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcustomer',
            name='phone_no',
            field=models.CharField(help_text='Phone no. can be max. of 15 characters', max_length=15),
        ),
    ]
