# Generated by Django 3.1.9 on 2022-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0044_auto_20220206_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='brand_name',
            field=models.CharField(db_index=True, help_text='brand name should be max. of 100 characters', max_length=200),
        ),
    ]
