# Generated by Django 3.1.9 on 2022-02-13 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_paymentmode'),
        ('party_payment', '0001_initial'),
        ('log_app', '0046_auto_20220213_1312'),
        ('purchase', '0011_auto_20220119_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpartypaymentdetail',
            name='party_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='party_payment.partypayment'),
        ),
        migrations.AddField(
            model_name='logpartypaymentdetail',
            name='payment_mode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_app.paymentmode'),
        ),
        migrations.AddField(
            model_name='logpartypayment',
            name='purchase_main',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchasemain'),
        ),
        migrations.AddField(
            model_name='logpartypayment',
            name='ref_party_clearance',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='party_payment.partypayment'),
        ),
    ]
