# Generated by Django 3.1.9 on 2022-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0048_auto_20220215_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='ws_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
