# Generated by Django 3.1.9 on 2022-02-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0050_logpopriority_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='logorderdetail',
            name='archived',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
    ]
