# Generated by Django 3.1.9 on 2022-03-13 04:34

import django.core.validators
from django.db import migrations, models
import src.custom_lib.functions.field_value_validation


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0055_auto_20220313_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='free_qty',
            field=models.IntegerField(blank=True, help_text='Null= True, blank =True', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='purchase_qty',
            field=models.IntegerField(blank=True, help_text='Null= True, blank =True', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='logpurchasedetail',
            name='qty',
            field=models.IntegerField(validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
        migrations.AlterField(
            model_name='logpurchaseorderdetail',
            name='qty',
            field=models.IntegerField(validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
        migrations.AlterField(
            model_name='logpurchaseorderreceiveddetail',
            name='qty',
            field=models.IntegerField(validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
        migrations.AlterField(
            model_name='logsaledetail',
            name='qty',
            field=models.IntegerField(validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
    ]
