# Generated by Django 3.2 on 2022-07-25 05:48

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0060_alter_logordermain_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBloodTest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, help_text=' blood test name can be max. of 100 characters and must be unique', max_length=100)),
                ('specimen', models.CharField(help_text='specimen can be max. of 100 characters', max_length=100)),
                ('department', models.CharField(help_text='department can be max. of 50 characters', max_length=50)),
                ('method', models.CharField(help_text='department can be max. of 100 characters', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Max value  price can be upto 9999999999.99', max_digits=12)),
                ('reporting', models.CharField(help_text='department can be max. of 100 characters', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
                ('history_user_id', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical blood test',
                'db_table': 'blood_test_log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LogBloodTestCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, help_text=' blood test category name can be max. of 100 characters and must be unique', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
                ('history_user_id', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical blood test category',
                'db_table': 'blood_test_category_log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LogTestPackage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(db_index=True, help_text=' blood test package name can be max. of 100 characters and must be unique', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Max value  price can be upto 9999999999.99', max_digits=12)),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
                ('history_user_id', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical test package',
                'db_table': 'test_package_log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
