# Generated by Django 3.2 on 2022-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0062_logbloodtestordermain'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbloodtestordermain',
            name='blood_test_order_no',
            field=models.CharField(db_index=True, default='hh', help_text=' Blood Test Order Id should be max. of 13 characters', max_length=20),
            preserve_default=False,
        ),
    ]
