# Generated by Django 3.2 on 2022-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0069_auto_20220726_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbloodtestordermain',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00 ', max_digits=12),
        ),
        migrations.AddField(
            model_name='logbloodtestordermain',
            name='archived',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='logbloodtestordermain',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00', max_digits=12),
        ),
        migrations.DeleteModel(
            name='LogBloodTestOrderDetail',
        ),
    ]
