# Generated by Django 3.2 on 2022-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0071_auto_20220726_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbloodtestordermain',
            name='is_blood_test',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='logbloodtestordermain',
            name='is_test_package',
            field=models.BooleanField(),
        ),
    ]
