# Generated by Django 3.1.9 on 2021-12-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strength',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strength',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='null = true , blank = true', null=True, on_delete=django.db.models.deletion.PROTECT, to='item.unit'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.supercategory'),
        ),
        migrations.AddField(
            model_name='popriority',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_priorities', to='company.company'),
        ),
        migrations.AddField(
            model_name='popriority',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popriority',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='medicineform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='generic_name',
            field=models.ManyToManyField(blank=True, to='item.GenericName'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='medicine_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.medicineform'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.ManyToManyField(to='item.ProductCategory'),
        ),
        migrations.AddField(
            model_name='genericname',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genericname',
            name='medicine_category',
            field=models.ManyToManyField(related_name='medicine_categories', to='item.MedicineCategory'),
        ),
        migrations.AddField(
            model_name='genericname',
            name='strength',
            field=models.ManyToManyField(to='item.Strength'),
        ),
        migrations.AlterUniqueTogether(
            name='popriority',
            unique_together={('priority', 'company'), ('supplier', 'company')},
        ),
    ]
