# Generated by Django 3.1.9 on 2022-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20220102_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, help_text='Item code should be max. of 10 characters', max_length=10, unique=True),
        ),
    ]
