# Generated by Django 3.1.9 on 2022-01-07 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0005_auto_20220103_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text=' Product Unit name can be max. of 50 characters and must be unique', max_length=50, unique=True)),
                ('short_form', models.CharField(help_text='short_form can be max. of 20 characters and must be unique', max_length=20, unique=True)),
                ('display_order', models.IntegerField(blank=True, default=0, help_text='Display order for ordering, default=0,blank= True, null= True', null=True)),
                ('active', models.BooleanField(default=True, help_text='By default active=True')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.ItemUnit'),
        ),
    ]
