# Generated by Django 3.1.9 on 2022-02-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20220130_1502'),
        ('item', '0015_auto_20220113_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='company.company'),
        ),
    ]
