# Generated by Django 3.1.9 on 2022-02-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20220201_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericname',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='item',
            name='generic_name',
        ),
    ]
