# Generated by Django 3.1.9 on 2022-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_genericstrength'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericname',
            name='strength',
            field=models.ManyToManyField(through='item.GenericStrength', to='item.Strength'),
        ),
    ]
