# Generated by Django 3.1.9 on 2022-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_genericname_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='generic_name',
            field=models.ManyToManyField(to='item.GenericStrength'),
        ),
    ]
