# Generated by Django 3.1.9 on 2022-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_auto_20220202_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericname',
            name='strength',
            field=models.ManyToManyField(related_name='strengths', through='item.GenericStrength', to='item.Strength'),
        ),
    ]
