# Generated by Django 3.1.9 on 2022-02-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20220202_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstrength',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generic_strength', to='item.strength'),
        ),
    ]
