# Generated by Django 3.1.9 on 2022-02-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_auto_20220203_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericname',
            name='strength',
        ),
    ]
