# Generated by Django 3.1.9 on 2022-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_auto_20220203_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericname',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='genericstrength',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='item',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='medicineform',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='strength',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='archive',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
        migrations.AlterUniqueTogether(
            name='strength',
            unique_together={('strength', 'unit')},
        ),
    ]
