# Generated by Django 3.1.9 on 2022-02-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_auto_20220206_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericname',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='genericstrength',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='medicinecategory',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='medicineform',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='strength',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='supercategory',
            old_name='archive',
            new_name='archived',
        ),
    ]
