# Generated by Django 3.1.9 on 2022-02-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0028_auto_20220206_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(help_text='item unit foreign key references from ItemUnit model', null=True, on_delete=django.db.models.deletion.PROTECT, to='item.itemunit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='item.ProductCategory'),
        ),
    ]
