# Generated by Django 3.1.9 on 2022-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_auto_20220211_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand_name',
            field=models.CharField(help_text='brand name should be max. of 100 characters', max_length=200, unique=True),
        ),
    ]
