# Generated by Django 3.1.9 on 2022-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0031_auto_20220214_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ws_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
