# Generated by Django 3.1.9 on 2021-12-29 12:56

import django.core.validators
from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('customer_seq_type', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS'), (3, 'SEQUENTIAL')], default=2, help_text='where 1=AD,2=BS,3=SEQUENTIAL  and default=2')),
                ('fiscal_session_type', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS')], default=2, help_text='Where 1 = AD , 2 = BS and default=2')),
                ('calendar_system', models.PositiveIntegerField(choices=[(1, 'AD'), (2, 'BS')], default=2, help_text='Where 1 = AD , 2 = BS and default=2')),
                ('enable_print', models.BooleanField(default=True)),
                ('print_preview', models.BooleanField(default=True)),
                ('billing_time_restriction', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('first_day_of_week', models.PositiveIntegerField(choices=[(1, 'SUNDAY'), (2, 'MONDAY'), (3, 'TUESDAY'), (4, 'WEDNESDAY'), (5, 'THURSDAY'), (6, 'FRIDAY'), (7, 'SATURDAY')], default=1, help_text='where 1 = Sunday ---- 7 =Saturday')),
                ('tax_system', models.PositiveIntegerField(choices=[(1, 'VAT'), (2, 'PAN')], default=1, help_text='where 1=VAT, 2=PAN')),
                ('round_off_limit', models.PositiveIntegerField(default=2)),
                ('round_off_purchase', models.BooleanField(default=True)),
                ('round_off_sale', models.BooleanField(default=True)),
                ('item_expiry_date_sale_threshold', models.PositiveIntegerField(default=30)),
                ('tax_applicable', models.BooleanField(default=True)),
                ('tax_rate', models.FloatField(default=0.0, help_text='Tax rate', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='Organization name should be maximum of 100 characters', max_length=100, unique=True)),
                ('address', models.CharField(blank=True, help_text='Organization name should be maximum of 100 characters', max_length=100, unique=True)),
                ('phone_no_1', models.CharField(blank=True, help_text='Phone no should be maximum of 15 characters', max_length=15, unique=True)),
                ('phone_no_2', models.CharField(blank=True, help_text='Phone no should be maximum of 15 characters', max_length=15)),
                ('mobile_no', models.CharField(blank=True, help_text='Mobile no should be maximum of 15 characters', max_length=15, unique=True)),
                ('pan_no', models.CharField(blank=True, help_text='PAN no. should be maximum of 15 characters', max_length=15, unique=True)),
                ('owner_name', models.CharField(blank=True, help_text='Owner name should be maximum of 50 characters', max_length=50, unique=True)),
                ('email', models.CharField(blank=True, help_text='Email Id. should be maximum of 70 characters', max_length=70, unique=True)),
                ('website_url', models.CharField(blank=True, help_text='Website address should be maximum of 50 characters', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='organization_setup/logo', validators=[src.core_app.models.validate_image])),
                ('favicon', models.ImageField(blank=True, upload_to='organization_setup/favicon', validators=[src.core_app.models.validate_image])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
