# Generated by Django 3.1.9 on 2022-01-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20220109_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salemain',
            name='ref_purchase_main',
        ),
    ]
