# Generated by Django 3.1.9 on 2022-01-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0011_auto_20220117_1429'),
        ('sale', '0008_remove_salemain_ref_purchase_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='ref_customer_order_detail',
            field=models.ForeignKey(blank=True, help_text='null = True , blank = True', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_order.orderdetail'),
        ),
        migrations.AddField(
            model_name='salemain',
            name='ref_customer_order_main',
            field=models.ForeignKey(blank=True, help_text='null = True , blank = True', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_order.ordermain'),
        ),
    ]
