# Generated by Django 3.1.9 on 2022-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_auto_20220121_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemain',
            name='pay_type',
            field=models.PositiveIntegerField(choices=[(1, 'CASH'), (2, 'CREDIT')], default=1, help_text='Pay type like 1 = CASH, 2 = CREDIT'),
        ),
    ]
