# Generated by Django 3.1.9 on 2022-02-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220201_1133'),
        ('sale', '0010_salemain_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemain',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mains', to='customer.customer'),
        ),
    ]
