# Generated by Django 3.1.9 on 2022-03-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0012_orderdetail_archived'),
        ('sale', '0012_salepaymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemain',
            name='ref_customer_order_main',
            field=models.ForeignKey(blank=True, help_text='null = True , blank = True', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customer_order.ordermain'),
        ),
    ]
