# Generated by Django 3.1.9 on 2022-03-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20220313_1019'),
        ('sale', '0014_auto_20220313_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='purchase.purchasedetail'),
        ),
    ]
