# Generated by Django 3.2 on 2022-12-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0035_auto_20220313_1019'),
        ('sale', '0015_auto_20220316_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='item.item'),
        ),
    ]
