# Generated by Django 3.2 on 2022-07-25 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_test', '0002_auto_20220724_1548'),
        ('customer', '0005_auto_20220215_1033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestOrderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('delivery_status', models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'CANCELLED'), (3, 'BILLED'), (4, 'PACKED'), (5, 'DISPATCHED'), (6, 'DONE'), (7, 'BILLED & PENDING')], default=1, help_text='Where 1 = PENDING, 2 = CANCELLED,  3 = BILLED,  4 = BILLED & PENDING, 5 = PACKED, 6=DISPATCHED, 7=DONE, Default=1')),
                ('amount_status', models.PositiveIntegerField(choices=[(1, 'PAID'), (2, 'UNPAID')], default=2, help_text='Where 1 = PAID, 2 = UNPAID where default = 2')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total  amount default=0.00', max_digits=12)),
                ('order_location', models.CharField(help_text=' Order Location should be max. of 100 characters', max_length=100)),
                ('google_location', models.CharField(blank=True, help_text=' Google Location should be max. of 100 characters', max_length=100)),
                ('remarks', models.CharField(blank=True, help_text='Remarks should be max. of 100 characters', max_length=100)),
                ('blood_test', models.ManyToManyField(to='blood_test.BloodTest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_test_order', to='customer.customer')),
                ('delivery_person', models.ForeignKey(blank=True, help_text='null = True , blank = True, related name = delivery person', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blood_test_delivery_person', to=settings.AUTH_USER_MODEL)),
                ('test_package', models.ManyToManyField(to='blood_test.TestPackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
