# Generated by Django 3.2 on 2022-07-25 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_test', '0002_auto_20220724_1548'),
        ('blood_test_order', '0002_bloodtestordermain_blood_test_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtestordermain',
            name='blood_test',
        ),
        migrations.RemoveField(
            model_name='bloodtestordermain',
            name='test_package',
        ),
        migrations.CreateModel(
            name='BloodTestOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00 ', max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00 ', max_digits=12)),
                ('archived', models.BooleanField(default=False, help_text='By default= False')),
                ('blood_test', models.ManyToManyField(to='blood_test.BloodTest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('test_order_main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_test_order_details', to='blood_test_order.bloodtestordermain')),
                ('test_package', models.ManyToManyField(to='blood_test.TestPackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
