# Generated by Django 3.2 on 2022-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_test_order', '0006_bloodtestorderdetail_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtestorderdetail',
            name='qty',
        ),
        migrations.AddField(
            model_name='bloodtestorderdetail',
            name='is_blood_test',
            field=models.BooleanField(default=True, help_text='By default= True'),
        ),
        migrations.AddField(
            model_name='bloodtestorderdetail',
            name='is_test_package',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodtestorderdetail',
            name='archived',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bloodtestorderdetail',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='default = 0.00', max_digits=12),
        ),
    ]
