# Generated by Django 3.2 on 2022-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_test', '0002_auto_20220724_1548'),
        ('blood_test_order', '0010_auto_20220726_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtestordermain',
            name='blood_test',
            field=models.ManyToManyField(blank=True, to='blood_test.BloodTest'),
        ),
        migrations.AlterField(
            model_name='bloodtestordermain',
            name='is_blood_test',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bloodtestordermain',
            name='is_test_package',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bloodtestordermain',
            name='test_package',
            field=models.ManyToManyField(blank=True, to='blood_test.TestPackage'),
        ),
    ]
