# Generated by Django 3.1.9 on 2021-12-29 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(help_text='name can be max. of 40 characters', max_length=40)),
                ('feature_brand', models.BooleanField(default=True, help_text='by default active = True')),
                ('phone_no', models.CharField(help_text='Phone no. can be max. of 15 characters', max_length=15)),
                ('address', models.CharField(blank=True, help_text='Address can be max. of 50 characters and blank = True', max_length=50)),
                ('brand_image', models.ImageField(blank=True, upload_to='brand_image')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='default=0.0 and can be upto 100.00', max_digits=5)),
                ('purchase_cc_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True, help_text='by default active = True')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
