# Generated by Django 3.1.9 on 2022-01-03 13:51

from django.db import migrations, models
import src.company.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brand_image',
            field=models.ImageField(blank=True, help_text='blank  true', upload_to='brand_image', validators=[src.company.models.validate_image]),
        ),
    ]
