# Generated by Django 3.1.9 on 2022-01-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220103_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='name can be max. of 150 characters', max_length=150),
        ),
    ]
