# Generated by Django 3.1.9 on 2022-01-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20220126_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Phone no. can be max. of 15 characters and blank = True, null = True', max_length=15, null=True),
        ),
    ]
