# Generated by Django 3.1.9 on 2022-01-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20211229_1841'),
        ('purchase', '0003_auto_20220103_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemain',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='null= True, blank = True', null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
    ]
