# Generated by Django 3.1.9 on 2022-01-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20220117_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemain',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text=' discount amount default=0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasemain',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text=' vat amount default=0.00', max_digits=12),
        ),
    ]
