# Generated by Django 3.1.9 on 2022-02-13 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_auto_20220126_1149'),
        ('purchase', '0011_auto_20220119_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemain',
            name='pay_type',
            field=models.PositiveIntegerField(choices=[(1, 'CASH'), (2, 'CREDIT')], default=1, help_text='Pay type like 1=CASH, 2=CREDIT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasemain',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='null= True, blank = True', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_mains', to='supplier.supplier'),
        ),
    ]
