# Generated by Django 3.1.9 on 2022-02-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20220213_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemain',
            name='bill_date_ad',
            field=models.DateField(blank=True, help_text='Bill Date AD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasemain',
            name='bill_date_bs',
            field=models.CharField(blank=True, help_text='Bill Date BS', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasemain',
            name='bill_no',
            field=models.CharField(blank=True, help_text='Bill no.', max_length=20),
        ),
    ]
