# Generated by Django 3.1.9 on 2021-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first Name should be maximum of 50 characters', max_length=50)),
                ('last_name', models.CharField(blank=True, help_text='last Name should be maximum of 50 characters', max_length=50)),
                ('home_address', models.CharField(blank=True, help_text='home address should be maximum of 255 characters', max_length=255)),
                ('home_google_location', models.CharField(blank=True, help_text=' home google location should be maximum of 255 characters', max_length=255)),
                ('office_address', models.CharField(blank=True, help_text=' office address should be maximum of 255 characters', max_length=255)),
                ('office_google_location', models.CharField(blank=True, help_text='office  google location should be maximum of 255 characters', max_length=255)),
                ('phone_no', models.CharField(help_text='Phone no. can be max. of 15 characters', max_length=15)),
                ('client_no', models.CharField(blank=True, max_length=15, null=True)),
                ('alt_phone_no', models.CharField(blank=True, help_text=' Alternative Phone no. can be max. of 15 characters and blank= True', max_length=15, null=True)),
                ('created_date_ad', models.DateTimeField(blank=True, null=True)),
                ('created_date_bs', models.CharField(blank=True, help_text='Blank= True, Null = True', max_length=10, null=True)),
            ],
        ),
    ]
