# Generated by Django 3.1.9 on 2022-01-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(help_text='Phone no. can be max. of 15 characters and unique = True', max_length=15, unique=True),
        ),
    ]
