# Generated by Django 3.1.9 on 2022-01-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_auto_20211229_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='unit',
        ),
    ]
