# Generated by Django 3.1.9 on 2022-01-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0008_auto_20220111_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='informed',
            field=models.BooleanField(default=False, help_text='default = false'),
        ),
    ]
