# Generated by Django 3.1.9 on 2022-01-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('customer_order', '0009_orderdetail_informed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_order', to='customer.customer'),
        ),
    ]
