# Generated by Django 3.1.9 on 2022-01-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0010_auto_20220116_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='delivery_status',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'CANCELLED'), (3, 'BILLED'), (4, 'PACKED'), (5, 'DISPATCHED'), (6, 'DONE')], default=1, help_text='Where 1 = PENDING, 2 = CANCELLED,  3 = BILLED,  4 = PACKED, 5 =DISPATCHED, 6=DONE,  Default=1'),
        ),
    ]
