# Generated by Django 3.1.9 on 2022-03-13 04:28

from django.db import migrations, models
import src.custom_lib.functions.field_value_validation


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0012_orderdetail_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='qty',
            field=models.IntegerField(validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
    ]
