# Generated by Django 3.1.9 on 2022-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0013_auto_20220313_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='By default= False'),
        ),
    ]
