# Generated by Django 3.2 on 2022-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0014_orderdetail_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='delivery_status',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'CANCELLED'), (3, 'BILLED'), (4, 'BILLED & PENDING'), (5, 'PACKED'), (6, 'DISPATCHED'), (7, 'DONE')], default=1, help_text='Where 1 = PENDING, 2 = CANCELLED,  3 = BILLED,  4 = BILLED & PENDING, 5 = PACKED, 6=DISPATCHED, 7=DONE, Default=1'),
        ),
    ]
