# Generated by Django 3.2 on 2022-05-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0015_alter_ordermain_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='delivery_status',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'CANCELLED'), (3, 'BILLED'), (4, 'PACKED'), (5, 'DISPATCHED'), (6, 'DONE'), (7, 'BILLED & PENDING')], default=1, help_text='Where 1 = PENDING, 2 = CANCELLED,  3 = BILLED,  4 = BILLED & PENDING, 5 = PACKED, 6=DISPATCHED, 7=DONE, Default=1'),
        ),
    ]
